apiVersion: apps/v1
kind: Deployment
metadata:
  name: website2-deployment
  labels:
    app: website2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website2
  template:
    metadata:
      labels:
        app: website2
    spec:
      containers:
      - name: website2
        image: saxenasamarth/website2:latest
        ports:
        - containerPort: 80
