apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: website2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008